version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDARABASE: ${POSTGRES_DB:-db}
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432

  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    command: bash ./run.sh
    ports:
      - 127.0.0.1:${WEB_PORT:-5000}:5000
    env_file: .env
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

volumes:
  db_data:
