version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/home/app/web
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app

  db:
    image: mysql:8.0
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'django'
       MYSQL_PASSWORD: 'django'
       MYSQL_ROOT_PASSWORD: '22082003'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app

  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/django_project
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    networks:
      - app
    environment:
      PYTHONUNBUFFERED: 1

networks:
  app:
    driver: bridge