# Generated by Django 3.1.1 on 2022-12-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
